language: node_js
node_js:
  - 0.4
  - 0.6
before_install:
  - mongo bootstrap --eval 'db.user.insert({ "_id" : 1, "created_at" : ISODate("2011-10-08T21:43:43.934Z"), "email" : "admin@example.com", "is_admin" : "on", "is_root" : "on", "modified_at" : ISODate("2012-01-15T18:26:40.183Z"), "name" : "Admin", "password" : "", "username" : "Admin" });'
